# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e379b50832e9fb23a07a60a681c70d0a7d0a2a7c6459b28e68fecde0332e06c9ec926a687bac97b7c0d90114a9f83659bb7343ccca0aebc2bc60498ecf8bce

test:
  secret_key_base: efb042cc816cdfe745a8e34c1c720b56ae8ec127b4574fb6db2042020943f31623bd336388d3ffd1aef2a60fd22f365f4f74102584c2cbe940aac578aef70061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
